/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResponseFramePanel.java
 *
 * Created on 09.03.2010, 09:50:58
 */
package net.sf.mbus4j.slaves.ui;

import java.awt.Component;
import net.sf.mbus4j.dataframes.ApplicationReset;
import net.sf.mbus4j.dataframes.RequestClassXData;
import net.sf.mbus4j.dataframes.ResponseFrameContainer;
import net.sf.mbus4j.dataframes.UserDataResponse;
import net.sf.mbus4j.dataframes.datablocks.DataBlock;
import net.sf.mbus4j.dataframes.datablocks.vif.Vife;
import net.sf.mbus4j.dataframes.datablocks.vif.VifePrimary;

/**
 *
 * @author aploese
 */
public class ResponseFramePanel extends javax.swing.JScrollPane {

    /** Creates new form ResponseFramePanel */
    public ResponseFramePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        responsePanel = new javax.swing.JPanel();
        requestPanel = new javax.swing.JPanel();
        selectPanel = new javax.swing.JPanel();

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        responsePanel.setName("responsePanel"); // NOI18N
        responsePanel.setLayout(new javax.swing.BoxLayout(responsePanel, javax.swing.BoxLayout.PAGE_AXIS));
        jTabbedPane1.addTab("Response", responsePanel);

        requestPanel.setName("requestPanel"); // NOI18N
        requestPanel.setLayout(new javax.swing.BoxLayout(requestPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jTabbedPane1.addTab("Request", requestPanel);

        selectPanel.setName("selectPanel"); // NOI18N
        selectPanel.setLayout(new javax.swing.BoxLayout(selectPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jTabbedPane1.addTab("Select", selectPanel);

        setViewportView(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JPanel responsePanel;
    private javax.swing.JPanel selectPanel;
    // End of variables declaration//GEN-END:variables
    private ResponseFrameContainer rfc;


    void setResponseFrameContainer(ResponseFrameContainer rfc) {
//        if (true) return;
        this.rfc = rfc;
        responsePanel.removeAll();
        if (rfc.getResponseFrame() instanceof UserDataResponse) {
            UserDataResponse response = (UserDataResponse) rfc.getResponseFrame();
            UserDataResponsePanel panel = new UserDataResponsePanel();
            panel.setUserDataResponse(response, rfc.getName());
            responsePanel.add(panel);
            for (DataBlock db : response) {
                DataBlockPanel dbp = new DataBlockPanel();
                dbp.setVifes((Vife[])VifePrimary.values());
                dbp.setDataBlock(db);
                responsePanel.add(dbp);
            }
        }

        requestPanel.removeAll();
        if (rfc.getRequestFrame() instanceof RequestClassXData) {
            RequestClassXData request = (RequestClassXData) rfc.getRequestFrame();
            RequestClassXDataPanel panel = new RequestClassXDataPanel();
            panel.setRequestClassXData(request);
            requestPanel.add(panel);
        }

        selectPanel.removeAll();
        if (rfc.getSelectFrame() instanceof ApplicationReset) {
            ApplicationReset appReset = (ApplicationReset) rfc.getSelectFrame();
            ApplicationResetPanel panel = new ApplicationResetPanel();
            panel.setApplicationReste(appReset);
            selectPanel.add(panel);
            for (DataBlock db : appReset) {
                DataBlockPanel dbp = new DataBlockPanel();
                dbp.setDataBlock(db);
                selectPanel.add(dbp);
            }
        }
    }

    void commitChanges() {
        for (Component c : responsePanel.getComponents()) {
            if (c instanceof UserDataResponsePanel) {
              ((UserDataResponsePanel)c).commitChanges();
               rfc.setName(((UserDataResponsePanel)c).getFrameName());
            } else if (c instanceof DataBlockPanel) {
              ((DataBlockPanel)c).commitChanges();
            }
        }
        for (Component c : requestPanel.getComponents()) {
            if (c instanceof RequestClassXDataPanel) {
              ((RequestClassXDataPanel)c).commitChanges();
            } else if (c instanceof DataBlockPanel) {
              ((DataBlockPanel)c).commitChanges();
            }
        }
        for (Component c : selectPanel.getComponents()) {
            if (c instanceof ApplicationResetPanel) {
              ((ApplicationResetPanel)c).commitChanges();
            } else if (c instanceof DataBlockPanel) {
              ((DataBlockPanel)c).commitChanges();
            }
        }
    }

    public String getFrameName() {
        return rfc.getName();
    }

}
