/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RequestClassXDataPanel.java
 *
 * Created on 10.03.2010, 10:33:10
 */

package net.sf.mbus4j.slaves.ui;

import net.sf.mbus4j.dataframes.Frame.ControlCode;
import net.sf.mbus4j.dataframes.RequestClassXData;

/**
 *
 * @author aploese
 */
public class RequestClassXDataPanel extends javax.swing.JPanel {

    /** Creates new form RequestClassXDataPanel */
    public RequestClassXDataPanel() {
        initComponents();
        controlCodeComboBox.removeAllItems();
        for (ControlCode cc : ControlCode.values()) {
            controlCodeComboBox.addItem(cc);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlCodeLabel = new javax.swing.JLabel();
        controlCodeComboBox = new javax.swing.JComboBox();

        controlCodeLabel.setText("ControlCode:");
        controlCodeLabel.setName("controlCodeLabel"); // NOI18N

        controlCodeComboBox.setName("controlCodeComboBox"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlCodeLabel)
                    .addComponent(controlCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox controlCodeComboBox;
    private javax.swing.JLabel controlCodeLabel;
    // End of variables declaration//GEN-END:variables

    void setRequestClassXData(RequestClassXData rcd) {
        controlCodeComboBox.setSelectedItem(rcd.getControlCode());
    }

    public void commitChanges() {

    }

}
