package net.sf.mbus4j.master.ui;

/*
 * #%L
 * mbus4j-master-ui
 * %%
 * Copyright (C) 2009 - 2014 MBus4J
 * %%
 * mbus4j - Drivers for the M-Bus protocol - http://mbus4j.sourceforge.net/
 * Copyright (C) 2009-2014, mbus4j.sf.net, and individual contributors as indicated
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * 
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 * #L%
 */

import net.sf.mbus4j.dataframes.datablocks.DataBlock;
import net.sf.mbus4j.dataframes.datablocks.dif.DataFieldCode;
import net.sf.mbus4j.dataframes.datablocks.dif.FunctionField;
import net.sf.mbus4j.dataframes.datablocks.vif.ObjectAction;
import net.sf.mbus4j.dataframes.datablocks.vif.VifFB;
import net.sf.mbus4j.dataframes.datablocks.vif.VifFD;
import net.sf.mbus4j.dataframes.datablocks.vif.VifPrimary;
import net.sf.mbus4j.dataframes.datablocks.vif.VifTypes;
import net.sf.mbus4j.dataframes.datablocks.vif.Vife;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.border.TitledBorder;

/**
 *
 * @author aploese
 */
public class DataBlockPanel
        extends javax.swing.JPanel {

    /**
     * Creates new form DataBlockPanel
     */
    public DataBlockPanel() {
        initComponents();
        objectActionComboBox.removeAllItems();

        for (ObjectAction action : ObjectAction.values()) {
            objectActionComboBox.addItem(action);
        }

        dataFieldCodeComboBox.removeAllItems();

        for (DataFieldCode dfc : DataFieldCode.values()) {
            dataFieldCodeComboBox.addItem(dfc);
        }

        functionFieldComboBox.removeAllItems();

        for (FunctionField ff : FunctionField.values()) {
            functionFieldComboBox.addItem(ff);
        }

        vifTypeComboBox.removeAllItems();

        for (VifTypes value : VifTypes.values()) {
            vifTypeComboBox.addItem(value);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        objectActionLabel = new javax.swing.JLabel();
        dataFieldCodeLabel = new javax.swing.JLabel();
        exponentLabel = new javax.swing.JLabel();
        objectActionComboBox = new javax.swing.JComboBox();
        dataFieldCodeComboBox = new javax.swing.JComboBox();
        clearActionButton = new javax.swing.JButton();
        exponentTextField = new javax.swing.JFormattedTextField();
        functionFieldLabel = new javax.swing.JLabel();
        functionFieldComboBox = new javax.swing.JComboBox();
        storageNumberLabel = new javax.swing.JLabel();
        subunitLabel = new javax.swing.JLabel();
        tarifLabel = new javax.swing.JLabel();
        vifLabel = new javax.swing.JLabel();
        vifTypeComboBox = new javax.swing.JComboBox();
        storageNumberTextField = new javax.swing.JFormattedTextField();
        subunitTextField = new javax.swing.JFormattedTextField();
        tarifTextField = new javax.swing.JFormattedTextField();
        vifComboBox = new javax.swing.JComboBox();
        valueLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vifesList = new javax.swing.JList();
        vifesLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        objectActionLabel.setText("Action:");
        objectActionLabel.setName("objectActionLabel"); // NOI18N

        dataFieldCodeLabel.setText("DataFieldCode:");
        dataFieldCodeLabel.setName("dataFieldCodeLabel"); // NOI18N

        exponentLabel.setText("Exponent:");
        exponentLabel.setName("exponentLabel"); // NOI18N

        objectActionComboBox.setEnabled(false);
        objectActionComboBox.setName("objectActionComboBox"); // NOI18N
        objectActionComboBox.setPreferredSize(new java.awt.Dimension(10, 27));

        dataFieldCodeComboBox.setEnabled(false);
        dataFieldCodeComboBox.setName("dataFieldCodeComboBox"); // NOI18N
        dataFieldCodeComboBox.setPreferredSize(new java.awt.Dimension(10, 27));

        clearActionButton.setText("Clear");
        clearActionButton.setEnabled(false);
        clearActionButton.setName("clearActionButton"); // NOI18N
        clearActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearObjectAction(evt);
            }
        });

        exponentTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        exponentTextField.setEnabled(false);
        exponentTextField.setName("exponentTextField"); // NOI18N

        functionFieldLabel.setText("FunctionField:");
        functionFieldLabel.setName("functionFieldLabel"); // NOI18N

        functionFieldComboBox.setEnabled(false);
        functionFieldComboBox.setName("functionFieldComboBox"); // NOI18N
        functionFieldComboBox.setPreferredSize(new java.awt.Dimension(10, 27));

        storageNumberLabel.setText("StorageNumber:");
        storageNumberLabel.setName("storageNumberLabel"); // NOI18N

        subunitLabel.setText("Subunit:");
        subunitLabel.setName("subunitLabel"); // NOI18N

        tarifLabel.setText("Tarif:");
        tarifLabel.setName("tarifLabel"); // NOI18N

        vifLabel.setText("Vif:");
        vifLabel.setName("vifLabel"); // NOI18N

        vifTypeComboBox.setEnabled(false);
        vifTypeComboBox.setMinimumSize(new java.awt.Dimension(10, 27));
        vifTypeComboBox.setName("vifTypeComboBox"); // NOI18N
        vifTypeComboBox.setPreferredSize(new java.awt.Dimension(10, 27));
        vifTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vifTypeChanged(evt);
            }
        });

        storageNumberTextField.setName("storageNumberTextField"); // NOI18N

        subunitTextField.setName("subunitTextField"); // NOI18N

        tarifTextField.setName("tarifTextField"); // NOI18N

        vifComboBox.setEnabled(false);
        vifComboBox.setMinimumSize(new java.awt.Dimension(10, 27));
        vifComboBox.setName("vifComboBox"); // NOI18N
        vifComboBox.setPreferredSize(new java.awt.Dimension(10, 27));

        valueLabel.setText("Value:");
        valueLabel.setName("valueLabel"); // NOI18N

        valueTextField.setName("valueTextField"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        vifesList.setModel(new DefaultListModel());
        vifesList.setEnabled(false);
        vifesList.setName("vifesList"); // NOI18N
        jScrollPane1.setViewportView(vifesList);

        vifesLabel.setText("Vifes:");
        vifesLabel.setName("vifesLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vifLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objectActionLabel)
                            .addComponent(valueLabel)
                            .addComponent(tarifLabel)
                            .addComponent(subunitLabel)
                            .addComponent(storageNumberLabel)
                            .addComponent(exponentLabel)
                            .addComponent(dataFieldCodeLabel)
                            .addComponent(functionFieldLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(objectActionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearActionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(vifesLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataFieldCodeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 326, Short.MAX_VALUE)
                                    .addComponent(exponentTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                    .addComponent(functionFieldComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 326, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vifTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vifComboBox, 0, 163, Short.MAX_VALUE))
                                    .addComponent(tarifTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                    .addComponent(subunitTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                    .addComponent(storageNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                    .addComponent(valueTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objectActionLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(objectActionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearActionButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dataFieldCodeLabel)
                                    .addComponent(dataFieldCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(exponentLabel)
                                    .addComponent(exponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(functionFieldLabel)
                                    .addComponent(functionFieldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(storageNumberLabel)
                                    .addComponent(storageNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subunitLabel)
                                    .addComponent(subunitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarifLabel)
                            .addComponent(tarifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vifLabel)
                            .addComponent(vifTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vifComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(vifesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(valueLabel)
                    .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearObjectAction(java.awt.event.ActionEvent evt)    {//GEN-FIRST:event_clearObjectAction
        objectActionComboBox.setSelectedItem(null);
    }//GEN-LAST:event_clearObjectAction

    private void vifTypeChanged(java.awt.event.ActionEvent evt)    {//GEN-FIRST:event_vifTypeChanged
        vifComboBox.removeAllItems();

        if (vifTypeComboBox.getSelectedItem() == null) {
            return;
        }

        switch ((VifTypes) vifTypeComboBox.getSelectedItem()) {
            case ASCII:
                break;

            case PRIMARY:

                for (VifPrimary value : VifPrimary.values()) {
                    vifComboBox.addItem(value);
                }

                break;

            case FB_EXTENTION:

                for (VifFB value : VifFB.values()) {
                    vifComboBox.addItem(value);
                }

                break;

            case FD_EXTENTION:

                for (VifFD value : VifFD.values()) {
                    vifComboBox.addItem(value);
                }

                break;

            case MANUFACTURER_SPECIFIC:
                break;

            default:
        }
    }//GEN-LAST:event_vifTypeChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearActionButton;
    private javax.swing.JComboBox dataFieldCodeComboBox;
    private javax.swing.JLabel dataFieldCodeLabel;
    private javax.swing.JLabel exponentLabel;
    private javax.swing.JFormattedTextField exponentTextField;
    private javax.swing.JComboBox functionFieldComboBox;
    private javax.swing.JLabel functionFieldLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox objectActionComboBox;
    private javax.swing.JLabel objectActionLabel;
    private javax.swing.JLabel storageNumberLabel;
    private javax.swing.JFormattedTextField storageNumberTextField;
    private javax.swing.JLabel subunitLabel;
    private javax.swing.JFormattedTextField subunitTextField;
    private javax.swing.JLabel tarifLabel;
    private javax.swing.JFormattedTextField tarifTextField;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JFormattedTextField valueTextField;
    private javax.swing.JComboBox vifComboBox;
    private javax.swing.JLabel vifLabel;
    private javax.swing.JComboBox vifTypeComboBox;
    private javax.swing.JLabel vifesLabel;
    private javax.swing.JList vifesList;
    // End of variables declaration//GEN-END:variables
    private DataBlock db;

    public void setDataBlock(DataBlock db) {
        this.db = db;

        if (getBorder() instanceof TitledBorder) {
            if (db.getVif() != null) {
                ((TitledBorder) getBorder()).setTitle(db.getVif().getLabel());
            } else {
                ((TitledBorder) getBorder()).setTitle("Unknown");
            }
        }

        objectActionComboBox.setSelectedItem(db.getAction());
        dataFieldCodeComboBox.setSelectedItem(db.getDataFieldCode());
        exponentTextField.setText((db.getExponent() != null) ? db.getExponent().toString() : "");
        functionFieldComboBox.setSelectedItem(db.getFunctionField());
        storageNumberTextField.setText(String.valueOf(db.getStorageNumber()));
        subunitTextField.setText(String.valueOf(db.getSubUnit()));
        tarifTextField.setText(String.valueOf(db.getTariff()));

        if (db.getVif() == null) {
            vifTypeComboBox.setSelectedItem(null);
            vifComboBox.removeAllItems();
        } else {
            vifTypeComboBox.setSelectedItem(db.getVif().getVifType());
            vifTypeChanged(null);
            vifComboBox.setSelectedItem(db.getVif());
        }

        selectVifes(db.getVifes());
        valueTextField.setText(db.getValueAsString());

        //TODO VIFE Type ???
    }

    public void setVifes(Vife[] vifes) {
        DefaultListModel listModel = (DefaultListModel) vifesList.getModel();
        listModel.removeAllElements();

        for (int i = 0; i < vifes.length; i++) {
            listModel.add(i, vifes[i]);
        }
    }

    private void selectVifes(Vife[] vifes) {
        if (vifes.length == 0) {
            vifesList.setSelectedIndex(-1);

            return;
        }

        DefaultListModel listModel = (DefaultListModel) vifesList.getModel();
        int[] selected = new int[vifes.length];
        int selIndex = 0;

        for (int i = 0; i < vifes.length; i++) {
            int idx = listModel.indexOf(vifes[i]);

            if (idx > -1) {
                selected[selIndex++] = idx;
            }
        }

        vifesList.setSelectedIndices(selected);
    }

    public void commitChanges() {
        db.setValue(valueTextField.getText());
    }

    public static void main(String[] args) throws Exception {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        JFrame frame = new JFrame();
        frame.add(new DataBlockPanel());
        frame.validate();
        frame.setVisible(true);
    }
}
