package net.sf.mbus4j.master.ui;

/*
 * #%L
 * mbus4j-master-ui
 * %%
 * Copyright (C) 2009 - 2014 MBus4J
 * %%
 * mbus4j - Drivers for the M-Bus protocol - http://mbus4j.sourceforge.net/
 * Copyright (C) 2009-2014, mbus4j.sf.net, and individual contributors as indicated
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * 
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 * #L%
 */

import net.sf.mbus4j.dataframes.ApplicationReset;
import net.sf.mbus4j.dataframes.RequestClassXData;
import net.sf.mbus4j.dataframes.ResponseFrameContainer;
import net.sf.mbus4j.dataframes.UserDataResponse;
import net.sf.mbus4j.dataframes.datablocks.DataBlock;
import net.sf.mbus4j.dataframes.datablocks.vif.Vife;
import net.sf.mbus4j.dataframes.datablocks.vif.VifePrimary;

import java.awt.Component;

/**
 *
 * @author aploese
 */
public class ResponseFramePanel
        extends javax.swing.JScrollPane {

    /**
     * Creates new form ResponseFramePanel
     */
    public ResponseFramePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(  )
    {
        jTabbedPane1 = new javax.swing.JTabbedPane(  );
        responsePanel = new javax.swing.JPanel(  );
        requestPanel = new javax.swing.JPanel(  );
        selectPanel = new javax.swing.JPanel(  );

        jTabbedPane1.setName( "jTabbedPane1" ); // NOI18N

        responsePanel.setName( "responsePanel" ); // NOI18N
        responsePanel.setLayout( new javax.swing.BoxLayout( responsePanel, javax.swing.BoxLayout.PAGE_AXIS ) );
        jTabbedPane1.addTab( "Response", responsePanel );

        requestPanel.setName( "requestPanel" ); // NOI18N
        requestPanel.setLayout( new javax.swing.BoxLayout( requestPanel, javax.swing.BoxLayout.PAGE_AXIS ) );
        jTabbedPane1.addTab( "Request", requestPanel );

        selectPanel.setName( "selectPanel" ); // NOI18N
        selectPanel.setLayout( new javax.swing.BoxLayout( selectPanel, javax.swing.BoxLayout.PAGE_AXIS ) );
        jTabbedPane1.addTab( "Select", selectPanel );

        setViewportView( jTabbedPane1 );
    } // </editor-fold>//GEN-END:initComponents
      // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JPanel responsePanel;
    private javax.swing.JPanel selectPanel;

    // End of variables declaration//GEN-END:variables
    private ResponseFrameContainer rfc;

    void setResponseFrameContainer(ResponseFrameContainer rfc) {
//        if (true) return;
        this.rfc = rfc;
        responsePanel.removeAll();

        if (rfc.getResponseFrame() instanceof UserDataResponse) {
            UserDataResponse response = (UserDataResponse) rfc.getResponseFrame();
            UserDataResponsePanel panel = new UserDataResponsePanel();
            panel.setUserDataResponse(response,
                    rfc.getName());
            responsePanel.add(panel);

            for (DataBlock db : response) {
                DataBlockPanel dbp = new DataBlockPanel();
                dbp.setVifes((Vife[]) VifePrimary.values());
                dbp.setDataBlock(db);
                responsePanel.add(dbp);
                dbp.invalidate();
                responsePanel.invalidate();
            }
        }

        requestPanel.removeAll();

        if (rfc.getRequestFrame() instanceof RequestClassXData) {
            RequestClassXData request = (RequestClassXData) rfc.getRequestFrame();
            RequestClassXDataPanel panel = new RequestClassXDataPanel();
            panel.setRequestClassXData(request);
            requestPanel.add(panel);
        }

        selectPanel.removeAll();

        if (rfc.getSelectFrame() instanceof ApplicationReset) {
            ApplicationReset appReset = (ApplicationReset) rfc.getSelectFrame();
            ApplicationResetPanel panel = new ApplicationResetPanel();
            panel.setApplicationReste(appReset);
            selectPanel.add(panel);

            for (DataBlock db : appReset) {
                DataBlockPanel dbp = new DataBlockPanel();
                dbp.setDataBlock(db);
                selectPanel.add(dbp);
            }
        }
        invalidate();
    }

    void commitChanges() {
        for (Component c : responsePanel.getComponents()) {
            if (c instanceof UserDataResponsePanel) {
                ((UserDataResponsePanel) c).commitChanges();
                rfc.setName(((UserDataResponsePanel) c).getFrameName());
            } else if (c instanceof DataBlockPanel) {
                ((DataBlockPanel) c).commitChanges();
            }
        }

        for (Component c : requestPanel.getComponents()) {
            if (c instanceof RequestClassXDataPanel) {
                ((RequestClassXDataPanel) c).commitChanges();
            } else if (c instanceof DataBlockPanel) {
                ((DataBlockPanel) c).commitChanges();
            }
        }

        for (Component c : selectPanel.getComponents()) {
            if (c instanceof ApplicationResetPanel) {
                ((ApplicationResetPanel) c).commitChanges();
            } else if (c instanceof DataBlockPanel) {
                ((DataBlockPanel) c).commitChanges();
            }
        }
    }

    public String getFrameName() {
        return rfc.getName();
    }
}
